# Generated by Django 5.1.2 on 2024-11-19 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings_app', '0002_remove_booking_cancel_deadline_alter_booking_listing_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
